import React from "react";
import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import Navbar from "@/app/components/navbar/Navbar";
import Footer from "@/app/components/Footer";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Home - Vedant's Portfolio",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    const navBarLinks = [
        {title: "Home", link: "/"},
        {title: "About", link: "/about"},
        {title: "Stack", link: "/stack"},
        {title: "Projects", link: "/projects"},
        {title: "Resume", link: "/resume"},
        {title: "Contact", link: "/contact"}
    ]

    return (
        <html lang="en">
        <body className={inter.className}>
        <main>
            <Navbar links={navBarLinks}/>
            {children}
            <Footer />
        </main>
        </body>
        </html>
    );
}
